export { healthRoutes } from "./health"
export { userRoutes } from "./user"
export { gamesRoutes, gameVersionsRoutes, gameSyncRoutes } from "./games"
export { hardwareRoutes } from "./hardware"
export { performanceRoutes, performanceVerifyRoutes } from "./performance"
export { performanceSubmitRoutes } from "./performance-submit"
export { commentsRoutes } from "./comments"
export { gamesListingRoutes } from "./games-listing"
export { gameStatsRoutes } from "./game-stats"
export { hardwareStatsRoutes } from "./hardware-stats"
export { savedGamesRoutes } from "./saved-games"
export { reportRoutes } from "./reports"
export { contactRoutes } from "./contact"
export { adminReportRoutes } from "./admin-reports"
export { adminPerformanceRoutes } from "./admin-performance"
export { adminCommentRoutes } from "./admin-comments"
export { steamgridProxyRoutes } from "./steamgrid-proxy"
export { gamesManualRoutes } from "./games-manual"
export { compareRoutes } from "./compare"
export { playabilityRoutes } from "./playability"
export { steamReviewRoutes } from "./steam-reviews"
export { communitySuggestionRoutes } from "./community-suggestions"
export { savedFilterRoutes } from "./saved-filters"
export { dashboardRoutes } from "./dashboard"
